# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shop-chat-agent"
client_id = "400bcaa5ee4b55946864413ec4740515"
handle = "shop-chat-agent-v3-1"
application_url = "${SHOPIFY_APP_URL}"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2024-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Read and write products, variants and collections
write_products
# Read and write customers
write_customers
# Read and write orders
write_orders
# Read and write script tags
write_script_tags
# Read and write price rules
write_price_rules
# Read and write discount codes
write_discounts
# Read and write marketing events
write_marketing_events
# Read and write resource feedback
write_resource_feedbacks
# Read and write metafields
write_metafields
# Read and write themes
write_themes
# Read and write content
write_content
# Read and write online store pages
write_online_store_pages
# Read and write online store articles
write_online_store_articles
# Read and write online store blogs
write_online_store_blogs
# Read and write online store navigation
write_online_store_navigation
# Read and write online store redirects
write_online_store_redirects
# Read and write online store script tags
write_online_store_script_tags
# Read and write online store themes
write_online_store_themes
# Read and write online store pages
write_online_store_pages
# Read and write online store articles
write_online_store_articles
# Read and write online store blogs
write_online_store_blogs
# Read and write online store navigation
write_online_store_navigation
# Read and write online store redirects
write_online_store_redirects
# Read and write online store script tags
write_online_store_script_tags
# Read and write online store themes
write_online_store_themes

[auth]
redirect_urls = [
  "${SHOPIFY_APP_URL}/auth/callback",
  "${SHOPIFY_APP_URL}/auth/shopify/callback",
  "${SHOPIFY_APP_URL}/api/auth/callback"
]

[pos]
embedded = false
